language: c

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libtool libperl-dev
  - LIBTOOL_INFO="`which libtool` --version => $(`which libtool` --version)"
  - echo "LIBTOOL_INFO:$LIBTOOL_INFO"

before_script:
  - cd /tmp
  - wget ftp://ftp.freeradius.org/pub/radius/freeradius-1.1.8.tar.bz2
  - tar -jxvf freeradius-1.1.8.tar.bz2
  - cd freeradius-1.1.8
  - cat Make.inc.in
  - cd src/modules
  - ln -s $TRAVIS_BUILD_DIR rlm_ftress
  - echo "rlm_ftress" >> stable
#  - cd rlm_ftress
#  - ./autogen.sh

script:
  - cd /tmp/freeradius-1.1.8
  - ./configure --with-system-libtool --prefix=/opt/freeradius-1.1.8
# BRUTE-FORCE hack/workaround to force the use of /usr/bin/libtool;
# given ./configure --with-system-libtool seems to be ignored by travis-ci/ubuntu?
  - mv libtool libtool.crap
  - ln -s /usr/bin/libtool libtool
  - ls -la libtool
  - make
