language: c

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libtool libperl-dev
  - `which libtool` --version

before_script:
  - cd /tmp
  - wget ftp://ftp.freeradius.org/pub/radius/freeradius-1.1.8.tar.bz2
  - tar -jxvf freeradius-1.1.8.tar.bz2
  - cd freeradius-1.1.8
  - patch -p1 < $TRAVIS_BUILD_DIR/freeradius-1.1.8_broken-libtool.patch
  - cat Make.inc.in
  - cd src/modules
  - ln -s $TRAVIS_BUILD_DIR rlm_ftress
  - echo "rlm_ftress" >> stable
#  - cd rlm_ftress
#  - ./autogen.sh

script:
  - "cd /tmp/freeradius-1.1.8 && ./configure --with-system-libtool --prefix=/opt/freeradius-1.1.8 && make"
