sudo: false

language: c

compiler:
  - gcc

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libperl-dev

before_script:
# download & build libtool
  - cd /tmp
  - wget http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.xz
  - tar -Jxvf libtool-2.4.6.tar.xz
  - cd libtool-2.4.6
  - ./configure --prefix=/tmp/libtool-2.4.6_build
  - make && make install
  - export PATH=/tmp/libtool-2.4.6_build/bin:$PATH

# download & build FreeRADIUS
  - cd /tmp
  - wget ftp://ftp.freeradius.org/pub/radius/freeradius-1.1.8.tar.bz2
  - tar -jxvf freeradius-1.1.8.tar.bz2

# copy the whole project into $FREERADIUS_SRC/src/modules
  - cd freeradius-1.1.8/src/modules
  - cp -r $TRAVIS_BUILD_DIR rlm_ftress
  - echo "rlm_ftress" >> stable
  - cd rlm_ftress
  - autoreconf

script:
  - cd /tmp/freeradius-1.1.8 && ./configure --with-system-libtool && make
